[tool.ruff]
# Ignoruj katalogi, których nie chcemy sprawdzać
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
]
# Długość linii (zgodna z black/standardami)
line-length = 88
target-version = "py310"

[tool.ruff.lint]
# E: pycodestyle errors, F: Pyflakes (wykrywa błędy logiczne, np. nieużywane importy)
select = ["E", "F"]
ignore = []

# Konfiguracja per-plik
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["F401"]  # Ignoruj F401 TYLKO w plikach w folderze tests
"__init__.py" = ["F401"] # Ignoruj też w plikach init
